# Generated by Django 5.1.7 on 2025-10-09 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_response'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Response',
        ),
    ]
